# Generated by Django 5.0.6 on 2026-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('hospital_admin', 'Hospital Admin'), ('patient', 'Patient'), ('system_admin', 'System Admin')], default='donor', max_length=20),
        ),
    ]
