# Generated by Django 5.0.6 on 2026-04-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospitals.hospital'),
        ),
    ]
